### PR TITLE
Wordsmithing

### PR DESCRIPTION
**Pull request by jeremyf**

### CODE REVIEW

**Comment by kensanata** [comment]
Thanks! As I'm still writing the Referee Guide (cosmology and monsters in particular) I think there will be a lot of changes ahead. I hope that won't frustrate you. :)

**Comment by jeremyf** [comment]
As I was reading that became more clear. So I'll wait to do any editing.

I really like the work you've done. The Referee Guide is insightful for the
light touch procedures you use/suggest.

Jeremy Friesen

**Comment by kensanata** [comment]
Thanks!

**Comment by kensanata** [comment]
@jeremyf If would love it if you still felt like wordsmithing. I've stopped editing the document and I'm using it more and more in my sessions, so perhaps it is stable enough right now.

**Pull request merged**
